### ISSUE TITLE
capo pod crash when use trust user

### ISSUE THREAD

**Issue by Goend** [kubernetes-sigs/cluster-api-provider-openstack#1308]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
1.cloud config use trust user id
```
[Global]
auth-url=http://keystone.openstack.svc.cluster.local:80/v3
user-id=ba431dfe5880484db367d5ad5c7681be
password=6advh66qBYsxYqL6v8
trust-id=b368e1dc8a5b458cb6728166b7d7bc0b
region=RegionOne
```

**What did you expect to happen:**
1.Pod is Running

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
cloud-provider-openstack
```
type Config struct {
	Global            client.AuthOpts
	LoadBalancer      LoadBalancerOpts
	LoadBalancerClass map[string]*LBClass
	Route             RouterOpts
	Metadata          metadata.Opts
	Networking        NetworkingOpts
}
```
cluster-api-provider-openstack
```
// Cloud represents an entry in a clouds.yaml/public-clouds.yaml/secure.yaml file.
type Cloud struct {
	Cloud      string    `yaml:"cloud,omitempty" json:"cloud,omitempty"`
	Profile    string    `yaml:"profile,omitempty" json:"profile,omitempty"`
	AuthInfo   *AuthInfo `yaml:"auth,omitempty" json:"auth,omitempty"`
	AuthType   AuthType  `yaml:"auth_type,omitempty" json:"auth_type,omitempty"`
	RegionName string    `yaml:"region_name,omitempty" json:"region_name,omitempty"`
	Regions    []Region  `yaml:"regions,omitempty" json:"regions,omitempty"`

	// EndpointType and Interface both specify whether to use the public, internal,
	// or admin interface of a service. They should be considered synonymous, but
	// EndpointType will take precedence when both are specified.
	EndpointType string `yaml:"endpoint_type,omitempty" json:"endpoint_type,omitempty"`
	Interface    string `yaml:"interface,omitempty" json:"interface,omitempty"`

	// API Version overrides.
	IdentityAPIVersion string `yaml:"identity_api_version,omitempty" json:"identity_api_version,omitempty"`
	VolumeAPIVersion   string `yaml:"volume_api_version,omitempty" json:"volume_api_version,omitempty"`

	// Verify whether or not SSL API requests should be verified.
	Verify *bool `yaml:"verify,omitempty" json:"verify,omitempty"`

	// CACertFile a path to a CA Cert bundle that can be used as part of
	// verifying SSL API requests.
	CACertFile string `yaml:"cacert,omitempty" json:"cacert,omitempty"`

	// ClientCertFile a path to a client certificate to use as part of the SSL
	// transaction.
	ClientCertFile string `yaml:"cert,omitempty" json:"cert,omitempty"`

	// ClientKeyFile a path to a client key to use as part of the SSL
	// transaction.
	ClientKeyFile string `yaml:"key,omitempty" json:"key,omitempty"`
}
```

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by seanschneeweiss** [comment]
Could you share your pod logs with us, especially the part where it crashes.

**Comment by Goend** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14ea246]

goroutine 662 [running]:
sigs.k8s.io/cluster-api-provider-openstack/controllers.machineToInstanceSpec(0xc000de4800, 0xc0008a0fc0, 0xc000d64000, {0x0, 0x0})
        /workspace/controllers/openstackmachine_controller.go:509 +0x546
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackMachineReconciler).reconcileDelete(0x1a6c3f8, {0x1a6c3f8, 0xc0007b4120}, 0xc000b34600, 0xc000d64000, 0xc000dde1c0, 0xc000de4800, 0xc0008a0fc0, 0xc000d64000)
        /workspace/controllers/openstackmachine_controller.go:252 +0x68b
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackMachineReconciler).Reconcile(0xc0007414a0, {0x1a6c3f8, 0xc0007b4120}, {{{0xc000b1cb60, 0x1766dc0}, {0xc000b1cb50, 0x30}}})
        /workspace/controllers/openstackmachine_controller.go:157 +0xb05
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000014580, {0x1a6c3f8, 0xc0007b40f0}, {{{0xc000b1cb60, 0x1766dc0}, {0xc000b1cb50, 0x27f2cb0}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000014580, {0x1a6c350, 0xc000383500}, {0x16a4c00, 0xc000465000})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000014580, {0x1a6c350, 0xc000383500})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:223 +0x357
```

**Comment by Goend** [comment]
if i want to auth by openstack trust id,the code should be changed in provider.go, how to change it,could give me a example?

**Comment by apricote** [comment]
The error logs look exactly like #1264. Are you sure that the crash is related to using OpenStack Trust ID?

**Comment by Goend** [comment]
How do I populate the secret if I want to use the trust credentials, so I need help
like this 
![Screenshot from 2022-08-10 17-10-22](https://user-images.githubusercontent.com/40394339/183863651-0c8dc5b7-989c-48f9-a393-8bb11744a718.png)

**Comment by Goend** [comment]
I get it.I use one  wrong trust credentials,so it's wrong
