### ISSUE TITLE
capo-controller crashloop -  invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by fmoctezuma** [kubernetes-sigs/cluster-api-provider-openstack#1372]
/kind bug

**What steps did you take and what happened:**
1.- We created a new cluster successfully, 
2.- We tried to create a second cluster and capo-controller is now on crashloop, with the following error

```
I1105 13:45:07.697460       1 controller.go:178] controller/openstackcluster "msg"="Starting EventSource" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster" "source"="kind source: *v1beta1.Cluster"
I1105 13:45:07.697968       1 controller.go:186] controller/openstackcluster "msg"="Starting Controller" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster"
I1105 13:45:07.697274       1 controller.go:178] controller/openstackmachine "msg"="Starting EventSource" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine" "source"="kind source: *v1alpha5.OpenStackMachine"
I1105 13:45:07.698349       1 controller.go:178] controller/openstackmachine "msg"="Starting EventSource" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine" "source"="kind source: *v1beta1.Machine"
I1105 13:45:07.698379       1 controller.go:178] controller/openstackmachine "msg"="Starting EventSource" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine" "source"="kind source: *v1alpha5.OpenStackCluster"
I1105 13:45:07.698407       1 controller.go:178] controller/openstackmachine "msg"="Starting EventSource" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine" "source"="kind source: *v1beta1.Cluster"
I1105 13:45:07.698425       1 controller.go:186] controller/openstackmachine "msg"="Starting Controller" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1105 13:45:07.801556       1 controller.go:220] controller/openstackcluster "msg"="Starting workers" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster" "worker count"=10
I1105 13:45:07.802420       1 controller.go:220] controller/openstackmachine "msg"="Starting workers" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine" "worker count"=10
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x14eb2ae]

goroutine 383 [running]:
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackMachineReconciler).getInfraCluster(0xc000021aa0, {0x1a6c338, 0xc000522420}, 0xc00086e540, 0xc0000b0f00)
	/workspace/controllers/openstackmachine_controller.go:598 +0x6e
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackMachineReconciler).Reconcile(0xc000021aa0, {0x1a6c338, 0xc000522420}, {{{0xc00074b426, 0x1766dc0}, {0xc0001949d8, 0x30}}})
	/workspace/controllers/openstackmachine_controller.go:117 +0x6e9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0000b9c30, {0x1a6c338, 0xc0005223c0}, {{{0xc00074b426, 0x1766dc0}, {0xc0001949d8, 0x413c34}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000b9c30, {0x1a6c290, 0xc0005f5dc0}, {0x16a4c00, 0xc0001ac3e0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000b9c30, {0x1a6c290, 0xc0005f5dc0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:223 +0x357
```

```
kubectl get clusters
NAME     PHASE          AGE   VERSION
test1    Provisioned    13h
test2    Provisioning   11h
```

```
kubectl get pods -n capo-system
NAME                                       READY   STATUS             RESTARTS      AGE
capo-controller-manager-5fcf678668-xt2nh   0/1     CrashLoopBackOff   6 (56s ago)   8m44s
```

**What did you expect to happen:**
Capo-controller runs well when more than one cluster is added or deleted.

**Anything else you would like to add:**
This problem occurred when we tried to create a misconfigured cluster (which was not provisioned successfully because of YML misconfiguration)

I see a very similar previous bug, looks related but closed with no fix.
See [invalid memory address or nil pointer dereference capi-controller crash #698
](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/698)

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): **v0.6.3**
- Cluster-API version: **cluster-api-controller:v1.2.4**
- OpenStack version: **Train 20.0.3**
- Minikube/KIND version: **rke multinode k8s v1.24.4**
- Kubernetes version (use `kubectl version`):  **Client v1.22.2, Server 1.24.4**
- OS (e.g. from `/etc/os-release`):  Ubuntu 20.0.4

**Comment by jichenjc** [comment]
>>>create a misconfigured cluster (which was not provisioned successfully because of YML misconfiguration)

what's the misconfigured cluster? do you mind share the YAML file? 


```
func (r *OpenStackMachineReconciler) getInfraCluster(ctx context.Context, cluster *clusterv1.Cluster, openStackMachine *infrav1.OpenStackMachine) (*infrav1.OpenStackCluster, error) {
        openStackCluster := &infrav1.OpenStackCluster{}
        openStackClusterName := client.ObjectKey{
                Namespace: openStackMachine.Namespace,
                Name:      cluster.Spec.InfrastructureRef.Name,    ==>I am guessing we should validate this before usage but this is just guess ..
        }
        if err := r.Client.Get(ctx, openStackClusterName, openStackCluster); err != nil {
                return nil, err
        }
        return openStackCluster, nil
}

```

**Comment by fmoctezuma** [comment]
Thanks to have a look @jichenjc , the thing that was misconfigured on the second cluster was the DNS servers env variable. (I was using a not-reachable DNS server by the k8s management cluster/ k8s pods)
```
export OPENSTACK_DNS_NAMESERVERS=<DNS servers>
```
And a bad auth_url under the clouds.yaml

```
# Ansible managed
clouds:
  openstack:
    auth:
      auth_url: https://<auth URL>
```

**Comment by jichenjc** [comment]
>>>And a bad auth_url under the clouds.yaml

ok, bad auth_url might lead to unexpected things, but anyway we should not panic..
maybe add a check as I pointed above would be helpful
