### ISSUE TITLE
Changing Bastion instance spec doesn't work

### ISSUE THREAD

**Issue by EmilienM** [kubernetes-sigs/cluster-api-provider-openstack#1855]
/kind bug

**What steps did you take and what happened:**
* Deploy a cluster with a bastion
* Once the cluster is deployed, edit OpenStackCluster.Spec to disable the bastion like it's [documented](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/5cc483bfc6eae8a8b8a67b32e9b7af0bafa473ca/api/v1alpha8/openstackcluster_types.go#L157-L159). So later we can re-create it with another spec (e.g. new flavor).
* Removing `OpenStackCluster.Spec.Bastion` produces an error in CAPO:

```
I0202 02:37:59.557716      20 controller.go:115] "Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="default/development-10884-rm62s" namespace="default" name="development-10884-rm62s" reconcileID="e0ebc724-7686-42ee-80fc-ce9984c1beb5"
```
(Here CAPO crashed in my lab, I had to restart it).

* Ok this time let's just switch `enabled` to False:
The bastion is removed and re-created immediately!
And `enabled` is True again (by itself).

**What did you expect to happen:**
The bastion should be deleted, so we can re-create it with a new spec.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): current main
- Logs from when we delete the bastion to when it's re-created: https://hastebin.com/share/sabasopulu.python

**Comment by mdbooth** [comment]
Have you got the stack trace? If we've got the stack trace it'll normally point directly to the bug.

**Comment by EmilienM** [comment]
> Have you got the stack trace? If we've got the stack trace it'll normally point directly to the bug.

Logs from when we delete the bastion to when it's re-created: https://hastebin.com/share/sabasopulu.python

**Comment by EmilienM** [comment]
> > > Have you got the stack trace? If we've got the stack trace it'll normally point directly to the bug.
> > 
> > 
> > Logs from when we delete the bastion to when it's re-created: https://hastebin.com/share/sabasopulu.python
> 
> I don't see a stack trace. Do you have the stack trace?

No trace, no error :cry:

**Comment by viktor-f** [comment]
I got a similar (maybe the same) error today when I tried to remove a bastion host. This is the last 2 logs of the capo controller pod.
```
I0206 08:51:48.033845       1 openstackcluster_controller.go:312] "Reconciling Bastion" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" co
ntrollerKind="OpenStackCluster" OpenStackCluster="capi-cluster/viktor-capi-elastx-sc" namespace="capi-cluster" name="viktor-capi-elastx-sc" reconcileID="6cbf2347-5dca-4de
9-8646-6f902a45bd3a" cluster="viktor-capi-elastx-sc"                                                                                                                      
I0206 08:51:48.582046       1 controller.go:115] "Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" controller="openstackc
luster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="capi-cluster/viktor-capi-elastx-sc" namespace="capi-cluster"
 name="viktor-capi-elastx-sc" reconcileID="6cbf2347-5dca-4de9-8646-6f902a45bd3a"                                                                                          
panic: runtime error: invalid memory address or nil pointer dereference [recovered]                                                                                       
        panic: runtime error: invalid memory address or nil pointer dereference                                                                                           
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1c0b8a4]                                                                                                  
                                                                                                                                                                          
goroutine 376 [running]:                                                                                                                                                  
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()                                                                                    
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:116 +0x1fa                                                               
panic({0x1e1a4e0, 0x35bd790})                                                                                                                                             
        /usr/local/go/src/runtime/panic.go:884 +0x213                                                                                                                     
sigs.k8s.io/cluster-api-provider-openstack/controllers.bastionToInstanceSpec(0xc000681000, {0xc0005e6840?, 0xc000681000?})                                                
        /workspace/controllers/openstackcluster_controller.go:393 +0xc4                                                                                                   
sigs.k8s.io/cluster-api-provider-openstack/controllers.deleteBastion({0x2466e58?, 0xc0011f5040?}, 0xc000cb0ea0, 0xc000681000)                                             
        /workspace/controllers/openstackcluster_controller.go:240 +0x3c5                                                                                                  
sigs.k8s.io/cluster-api-provider-openstack/controllers.reconcileBastion({0x2466e58, 0xc0011f5040}, 0xc000cb0ea0, 0xc000681000)                                            
        /workspace/controllers/openstackcluster_controller.go:315 +0xbf6                                                                                                  
sigs.k8s.io/cluster-api-provider-openstack/controllers.reconcileNormal({0x2466e58, 0xc0011f5040}, 0x0?, 0xc000681000)                                                     
        /workspace/controllers/openstackcluster_controller.go:280 +0x125                                                                                                  
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackClusterReconciler).Reconcile(0xc000a983c0, {0x245ddb8, 0xc000638e10}, {{{0xc0009bf9b0?, 0x0?}, {0xc0003b
a8d0?, 0xc000d35d48?}}})                                                                                                                                                  
        /workspace/controllers/openstackcluster_controller.go:127 +0x5e6                                                                                                  
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x2463430?, {0x245ddb8?, 0xc000638e10?}, {{{0xc0009bf9b0?, 0xb?}, {0xc0003ba8d0?, 0x0?}}}) 
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119 +0xc8                                                                
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000168140, {0x245dd10, 0xc0002d2dc0}, {0x1ee04e0?, 0xc0008fe4c0?})               
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316 +0x3ca                                                               
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000168140, {0x245dd10, 0xc0002d2dc0})                                         
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266 +0x1d9                                                               
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()                                                                                      
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227 +0x85                                                                
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2                                                                               
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:223 +0x587
```

**Comment by viktor-f** [comment]
This happened when I tried to delete the bastion host by removing the whole bastion config block from the openstackcluster object.
I managed to "solve" this by adding the bastion block again. But it was a bit annoying to do since modifying the openstackcluster object requires the capo controller to be running and this problem was causing the controller to crash a few seconds after it restarted. So I had to time the update to the restart of the controller pod.

It did manage to delete the floating IP before crashing. But then when I re-added the bastion config it did not re-create the floating ip. So I set enabled to false and then true again, that managed to delete everything and recreate it.

**Comment by viktor-f** [comment]
For reference: I'm running v0.9.0 of the capo controller

**Comment by EmilienM** [comment]
My initial bug report is invalid, I'm sorry for this. I was using a ClusterClass and an OpenStackClusterTemplate (which is immutable) so to actually disable the bastion I had to create a new OpenStackClusterTemplate (with no bastion spec) and update the ClusterClass to use that new OpenStackClusterTemplate and it worked fine. The bastion was removed and everything is good.

Now, it seems like @viktor-f reported a valid trace and I'll take care of investigating this one this week and very likely provide a fix.

**Comment by EmilienM** [comment]
I have reproduced @viktor-f's error:

```
I0206 16:36:13.944202      20 controller.go:115] "Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="default/development-25319-cpf6t" namespace="default" name="development-25319-cpf6t" reconcileID="80490768-7a54-40d5-8aa2-30e60e415772"
```

I'll look into this and fix it.

**Comment by EmilienM** [comment]
BTW I could reproduce the panic on latest main, so very likely a bug that will need to be fixed and backported.
