### ISSUE TITLE
invalid memory address or nil pointer dereference capi-controller crash

### ISSUE THREAD

**Issue by daydrim** [kubernetes-sigs/cluster-api-provider-openstack#698]
/kind bug

**What steps did you take and what happened:**
1. We created new cluster with yaml and cluster creates Successfully. State Provisioned - capi-quickstart
2. We tried to create second cluster but there is an error (YML misconfiguration) - then cluster stuck in provisioning state capi-multimaster
3. We tried to delete second cluster with kubectl delete cluster capi-multimaster - Cluster stuck in Deleting state
4. Then we create third cluster  c-multimaster and it stuks Provisioning then we got the Error:

```
kubectl logs -l control-plane=capo-controller-manager -n capo-system -c manager
I1127 10:28:29.603450       1 listener.go:44] controller-runtime/metrics "msg"="metrics server is starting to listen"  "addr"="127.0.0.1:8080"
I1127 10:28:29.605808       1 main.go:236] setup "msg"="starting manager"  "version"=""
I1127 10:28:29.606236       1 leaderelection.go:242] attempting to acquire leader lease  capo-system/controller-leader-election-capo...
I1127 10:28:29.606261       1 internal.go:356] controller-runtime/manager "msg"="starting metrics server"  "path"="/metrics"
I1127 10:28:47.097642       1 leaderelection.go:252] successfully acquired lease capo-system/controller-leader-election-capo
I1127 10:28:47.099899       1 controller.go:155] controller-runtime/controller "msg"="Starting EventSource" "controller"="openstackcluster" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"cloudsSecret":null,"cloudName":"","network":{},"subnet":{},"managedAPIServerLoadBalancer":false,"managedSecurityGroups":false,"controlPlaneEndpoint":{"host":"","port":0}},"status":{"ready":false}}}
I1127 10:28:47.103443       1 controller.go:155] controller-runtime/controller "msg"="Starting EventSource" "controller"="openstackmachine" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"cloudsSecret":null,"cloudName":"","flavor":"","image":""},"status":{"ready":false}}}
I1127 10:28:47.200589       1 controller.go:162] controller-runtime/controller "msg"="Starting Controller" "controller"="openstackcluster"
I1127 10:28:47.200678       1 controller.go:189] controller-runtime/controller "msg"="Starting workers" "controller"="openstackcluster" "worker count"=1
I1127 10:28:47.207198       1 controller.go:155] controller-runtime/controller "msg"="Starting EventSource" "controller"="openstackmachine" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"clusterName":"","bootstrap":{},"infrastructureRef":{}},"status":{"bootstrapReady":false,"infrastructureReady":false}}}
I1127 10:28:47.306641       1 openstackcluster_controller.go:114] controllers/OpenStackCluster "msg"="Reconciling Cluster delete" "cluster"="capi-multimaster" "namespace"="default" "openStackCluster"="capi-multimaster"
I1127 10:28:47.308573       1 controller.go:155] controller-runtime/controller "msg"="Starting EventSource" "controller"="openstackmachine" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"cloudsSecret":null,"cloudName":"","network":{},"subnet":{},"managedAPIServerLoadBalancer":false,"managedSecurityGroups":false,"controlPlaneEndpoint":{"host":"","port":0}},"status":{"ready":false}}}
I1127 10:28:47.310259       1 controller.go:155] controller-runtime/controller "msg"="Starting EventSource" "controller"="openstackmachine" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"controlPlaneEndpoint":{"host":"","port":0}},"status":{"infrastructureReady":false,"controlPlaneInitialized":false}}}
I1127 10:28:47.311778       1 controller.go:162] controller-runtime/controller "msg"="Starting Controller" "controller"="openstackmachine"
I1127 10:28:47.412075       1 controller.go:189] controller-runtime/controller "msg"="Starting workers" "controller"="openstackmachine" "worker count"=10
I1127 10:28:47.412346       1 openstackmachine_controller.go:90] controllers/OpenStackMachine "msg"="Machine Controller has not yet set OwnerRef" "namespace"="default" "openStackMachine"="capi-quickstart-controlplane"
I1127 10:28:47.415544       1 openstackmachine_controller.go:290] controllers/OpenStackMachine "msg"="Reconciling Machine create started" "cluster"="capi-quickstart" "machine"="capi-quickstart-md-0-55485b8db9-97m7d" "namespace"="default" "openStackCluster"="capi-quickstart" "openStackMachine"="capi-quickstart-md-0-9csmr"
I1127 10:28:47.416561       1 openstackmachine_controller.go:90] controllers/OpenStackMachine "msg"="Machine Controller has not yet set OwnerRef" "namespace"="default" "openStackMachine"="c-multimaster-controlplane"
I1127 10:28:47.417609       1 openstackmachine_controller.go:277] controllers/OpenStackMachine "msg"="Cluster infrastructure is not ready yet, requeuing machine" "cluster"="c-multimaster" "machine"="c-multimaster-md-0-6f4fff7445-nbqt7" "namespace"="default" "openStackCluster"="c-multimaster" "openStackMachine"="c-multimaster-md-0-btk8b"
I1127 10:28:47.412463       1 openstackmachine_controller.go:90] controllers/OpenStackMachine "msg"="Machine Controller has not yet set OwnerRef" "namespace"="default" "openStackMachine"="capi-multimaster-controlplane"
I1127 10:28:47.424633       1 openstackmachine_controller.go:290] controllers/OpenStackMachine "msg"="Reconciling Machine create started" "cluster"="capi-quickstart" "machine"="capi-quickstart-control-plane-2rxmp" "namespace"="default" "openStackCluster"="capi-quickstart" "openStackMachine"="capi-quickstart-control-plane-ndjzp"
E1127 10:28:47.812605       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 267 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x15fc640, 0x25ddbb0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/runtime/runtime.go:48 +0x82
panic(0x15fc640, 0x25ddbb0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackClusterReconciler).reconcileDelete(0xc0002469f0, 0x1a2b260, 0xc0000c0068, 0x1a3b280, 0xc000417410, 0xc00009be40, 0xc000738000, 0x0, 0xc0007284b0, 0x7, ...)
	/workspace/controllers/openstackcluster_controller.go:192 +0x1c9
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackClusterReconciler).Reconcile(0xc0002469f0, 0xc0007284b0, 0x7, 0xc0007284a0, 0x10, 0xc0005ba200, 0x0, 0x0, 0x0)
	/workspace/controllers/openstackcluster_controller.go:106 +0x6d7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004000b0, 0x16541e0, 0xc00072c180, 0x440500)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.11/pkg/internal/controller/controller.go:255 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004000b0, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.11/pkg/internal/controller/controller.go:231 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0004000b0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.11/pkg/internal/controller/controller.go:210 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000720750)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000720750, 0x3b9aca00, 0x0, 0x1, 0xc000162240)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000720750, 0x3b9aca00, 0xc000162240)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.11/pkg/internal/controller/controller.go:192 +0x468
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x148cf99]

goroutine 267 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/runtime/runtime.go:55 +0x105
panic(0x15fc640, 0x25ddbb0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackClusterReconciler).reconcileDelete(0xc0002469f0, 0x1a2b260, 0xc0000c0068, 0x1a3b280, 0xc000417410, 0xc00009be40, 0xc000738000, 0x0, 0xc0007284b0, 0x7, ...)
	/workspace/controllers/openstackcluster_controller.go:192 +0x1c9
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackClusterReconciler).Reconcile(0xc0002469f0, 0xc0007284b0, 0x7, 0xc0007284a0, 0x10, 0xc0005ba200, 0x0, 0x0, 0x0)
	/workspace/controllers/openstackcluster_controller.go:106 +0x6d7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004000b0, 0x16541e0, 0xc00072c180, 0x440500)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.11/pkg/internal/controller/controller.go:255 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004000b0, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.11/pkg/internal/controller/controller.go:231 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0004000b0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.11/pkg/internal/controller/controller.go:210 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000720750)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000720750, 0x3b9aca00, 0x0, 0x1, 0xc000162240)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000720750, 0x3b9aca00, 0xc000162240)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.11/pkg/internal/controller/controller.go:192 +0x468
```

```
kubectl get pods -A
	capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-7ffb7c9d77-pscgr       2/2     Running            0          80m
    capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-5b8cf46bb6-h64kg   2/2     Running            0          80m
    capi-system                         capi-controller-manager-559db48f6-6nndb                          2/2     Running            0          80m
    capi-webhook-system                 capi-controller-manager-76d9b5889c-ht2tf                         2/2     Running            0          80m
    capi-webhook-system                 capi-kubeadm-bootstrap-controller-manager-787cb85f58-m77z2       2/2     Running            0          80m
    capi-webhook-system                 capi-kubeadm-control-plane-controller-manager-86c44777c5-4thfr   2/2     Running            0          80m
    capi-webhook-system                 capo-controller-manager-5c586d49b6-555kn                         2/2     Running            0          80m
    capo-system                         capo-controller-manager-7595db778f-fc9pn                         1/2     CrashLoopBackOff   5          5m55s


kubectl get clusters
NAME               PHASE
c-multimaster      Provisioning
capi-multimaster   Deleting
capi-quickstart    Provisioned
```

**What did you expect to happen:**

Parallel Clusters deletion and provisioning do not Crash management cluster and capo-controller-manager

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This problem occurs only whe we try to delete misconfigured cluster (which was not provisioned successfuly because of YML misconfiguration)

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):  capi-openstack-controller:v0.3.3
- Cluster-API version: v0.3.11
- OpenStack version: Rocky
- Minikube/KIND version: kind v0.9.0 go1.15.2 linux/amd64
- Kubernetes version (use `kubectl version`): kubectl version 1.17.11
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.1 LTS

**Comment by hidekazuna** [comment]
Is this fixed by #693 ?

**Comment by lelvisl** [comment]
Need to test. Are you planing to release trivial version? Or we ned to build from current master state?

**Comment by hidekazuna** [comment]
we can use gcr.io/k8s-staging-capi-openstack/capi-openstack-controller repository.
https://console.cloud.google.com/gcr/images/k8s-staging-capi-openstack/GLOBAL/capi-openstack-controller

**Comment by jichenjc** [comment]
latest release is 0.3.3 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/

**Comment by sbueringer** [comment]
@lelvisl  Is the issue resolved?

**Comment by lelvisl** [comment]
sorry, i didn't checked. i think you can close this issue. 

if it will happens again i will open new issue and link this.

**Comment by sbueringer** [comment]
No problem

/close
