### ISSUE TITLE
capo-controller-manager crashing and not recovering due to wrong network UUID

### ISSUE THREAD

**Issue by Xenwar** [kubernetes-sigs/cluster-api-provider-openstack#749]
/kind bug

**What steps did you take and what happened:**
When creating a OpenStackMachineTemplate with an invalid network uuid, the controller crashes. 

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: OpenStackMachineTemplate
metadata:
  name: basic-1-control-plane
spec:
  template:
    spec:
      sshKeyName: <...>
      networks:
      - uuid: <Add an invalid UUID here>

```

**What did you expect to happen:**
That specific request fails and the capo-controller pod keeps running.

```
est-xenwar@xen-machine openstack-capo % kubectl get pods -A
NAMESPACE                           NAME                                                             READY   STATUS             RESTARTS   AGE
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-ddcc95784-2fs8k        2/2     Running            0          113m
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-d85dfd44c-8zvkv    2/2     Running            0          113m
capo-system                         capo-controller-manager-5548b9cd7-cgp5g                          1/2     CrashLoopBackOff   7          113m
cert-manager                        cert-manager-cainjector-fc6c787db-d4fm8                          1/1     Running            0          113m
```

```
**Anything else you would like to add:**
Logs shown below. 
I0222 13:23:26.873574       1 securitygroups.go:60] controllers/OpenStackCluster "msg"="Reconciling security groups" "namespace"="default" "openStackCluster"="basic-1" "cluster"="default-basic-1"
I0222 13:23:27.484099       1 openstackmachine_controller.go:353] controllers/OpenStackMachine "msg"="Reconciling Machine create started" "cluster"="basic-1" "machine"="basic-1-control-plane-j7wgl" "namespace"="default" "openStackCluster"="basic-1" "openStackMachine"="basic-1-control-plane-vqmw4" 
E0222 13:23:27.484528       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 329 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1652a60, 0x2715a50)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1652a60, 0x2715a50)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/services/compute.createPort(0xc00095d6d0, 0xc000b6c8e0, 0x7, 0xc000b31360, 0x1b, 0xc000944ce0, 0xc000475440, 0x0, 0x0, 0x0, ...)
	/workspace/pkg/cloud/services/compute/instance.go:477 +0x169
sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/services/compute.createInstance(0xc00095d6d0, 0xc000b6c8e0, 0x7, 0xc0009455b8, 0xc000b45540, 0x1, 0x1)
	/workspace/pkg/cloud/services/compute/instance.go:177 +0x16af
sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/services/compute.(*Service).InstanceCreate(0xc00095d6d0, 0xc000b6c8e0, 0x7, 0xc0003d8280, 0xc0001e58c0, 0xc000932000, 0xc0008a2000, 0x82f4, 0x0, 0x0, ...)
	/workspace/pkg/cloud/services/compute/instance.go:140 +0x48e
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackMachineReconciler).getOrCreate(0xc0006fd1d0, 0xc00095d6d0, 0xc0003d8280, 0xc0001e58c0, 0xc0007deea0, 0xc000932000, 0xc0008a2000, 0x82f4, 0x1aa8040, 0xc0002b2540, ...)
	/workspace/controllers/openstackmachine_controller.go:446 +0x1a4
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackMachineReconciler).reconcileNormal(0xc0006fd1d0, 0x1a97e60, 0xc000054070, 0x1aa8040, 0xc0002b2540, 0xc00009a9c0, 0xc0003d8280, 0xc0001e58c0, 0xc0007deea0, 0xc000932000, ...)
	/workspace/controllers/openstackmachine_controller.go:372 +0x460
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackMachineReconciler).Reconcile(0xc0006fd1d0, 0xc000ab61b0, 0x7, 0xc0009c5d60, 0x1b, 0xc000449000, 0x0, 0x0, 0x0)
	/workspace/controllers/openstackmachine_controller.go:143 +0x8e1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00016e000, 0x16acac0, 0xc00086c360, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:255 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00016e000, 0xc0006b4d00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:231 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00016e000)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:210 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003ce260)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003ce260, 0x3b9aca00, 0x0, 0xc0004f1c01, 0xc000200000)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0003ce260, 0x3b9aca00, 0xc000200000)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:192 +0x468
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14750f9]

goroutine 329 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1652a60, 0x2715a50)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/services/compute.createPort(0xc00095d6d0, 0xc000b6c8e0, 0x7, 0xc000b31360, 0x1b, 0xc000944ce0, 0xc000475440, 0x0, 0x0, 0x0, ...)
	/workspace/pkg/cloud/services/compute/instance.go:477 +0x169
sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/services/compute.createInstance(0xc00095d6d0, 0xc000b6c8e0, 0x7, 0xc0009455b8, 0xc000b45540, 0x1, 0x1)
	/workspace/pkg/cloud/services/compute/instance.go:177 +0x16af
sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/services/compute.(*Service).InstanceCreate(0xc00095d6d0, 0xc000b6c8e0, 0x7, 0xc0003d8280, 0xc0001e58c0, 0xc000932000, 0xc0008a2000, 0x82f4, 0x0, 0x0, ...)
	/workspace/pkg/cloud/services/compute/instance.go:140 +0x48e
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackMachineReconciler).getOrCreate(0xc0006fd1d0, 0xc00095d6d0, 0xc0003d8280, 0xc0001e58c0, 0xc0007deea0, 0xc000932000, 0xc0008a2000, 0x82f4, 0x1aa8040, 0xc0002b2540, ...)
	/workspace/controllers/openstackmachine_controller.go:446 +0x1a4
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackMachineReconciler).reconcileNormal(0xc0006fd1d0, 0x1a97e60, 0xc000054070, 0x1aa8040, 0xc0002b2540, 0xc00009a9c0, 0xc0003d8280, 0xc0001e58c0, 0xc0007deea0, 0xc000932000, ...)
	/workspace/controllers/openstackmachine_controller.go:372 +0x460
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackMachineReconciler).Reconcile(0xc0006fd1d0, 0xc000ab61b0, 0x7, 0xc0009c5d60, 0x1b, 0xc000449000, 0x0, 0x0, 0x0)
	/workspace/controllers/openstackmachine_controller.go:143 +0x8e1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00016e000, 0x16acac0, 0xc00086c360, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:255 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00016e000, 0xc0006b4d00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:231 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00016e000)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:210 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003ce260)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003ce260, 0x3b9aca00, 0x0, 0xc0004f1c01, 0xc000200000)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0003ce260, 0x3b9aca00, 0xc000200000)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:192 +0x468
```

**Environment:**

- Cluster API Provider OpenStack version: v0.3.4
- Kubernetes version: v1.19.1

**Comment by jichenjc** [comment]
I tried following but I can't reproduce the issue
```
Installing Provider="infrastructure-openstack" Version="v0.3.4" TargetNamespace="capo-system"

```

```

kind: OpenStackMachineTemplate
metadata:
  name: capi-openstack-control-plane
  namespace: default
spec:
  template:
    spec:
      floatingIP: 172.24.4.2
      cloudName: openstack
      cloudsSecret:
        name: capi-openstack-cloud-config
        namespace: default
      flavor: m1.medium
      image: ubuntu1910
      networks:
      - uuid: abc

```

```
kubectl logs capo-controller-manager-5548b9cd7-2bjzl -n capo-system -c manager
...
E0224 06:19:06.610211       1 openstackmachine_controller.go:460] controllers/OpenStackMachine "msg"="OpenStack instance cannot be created: error creating Openstack instance: create new server err: error creating Openstack instance: Expected HTTP response code [] when accessing [POST http://10.43.0.92/compute/v2.1/servers], but got 409 instead\n{\"conflictingRequest\": {\"code\": 409, \"message\": \"Multiple possible networks found, use a Network ID to be more specific.\"}}" "error"="UpdateError" "cluster"="capi-openstack-3" "machine"="capi-openstack-control-plane-8rkw8" "namespace"="default" "openStackCluster"="capi-openstack-3" "openStackMachine"="capi-openstack-control-plane-gxvvc"
E0224 06:19:06.619940       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="error creating Openstack instance: create new server err: error creating Openstack instance: Expected HTTP response code [] when accessing [POST http://10.43.0.92/compute/v2.1/servers], but got 409 instead\n{\"conflictingRequest\": {\"code\": 409, \"message\": \"Multiple possible networks found, use a Network ID to be more specific.\"}}" "controller"="openstackmachine" "name"="capi-openstack-control-plane-gxvvc" "namespace"="default"

```

```
network list 

+--------------------------------------+-------------------------------------------------+----------------------------------------------------------------------------+
| ID                                   | Name                                            | Subnets                                                                    |
+--------------------------------------+-------------------------------------------------+----------------------------------------------------------------------------+
| 1d5baff7-fa9d-4171-ba8b-336d795c50d2 | private                                         | 5d267b6d-39d2-4b17-b16b-95335399c5c3, 72fd6fe3-bc4f-4a4d-97eb-48f27a1dccab |
| 54582a9b-3a3c-43ea-bdbd-bb8586630cd6 | k8s-clusterapi-cluster-default-capi-openstack-3 | 7c7966fb-0786-48eb-a5aa-f9ad2b5377bf                                       |
| b7bd6cb7-90b2-4447-9efa-ffa3452bc034 | shared                                          | 5480c47b-018c-4946-a7d2-099802ff35a1                                       |
| e31c8e48-5a48-4871-b32a-2235a0b65a25 | public                                          | 380e61a5-ad07-488f-99cc-828d8dcb61bf, 5f14d4c8-b327-40ab-b064-681fcb91d51c |
+--------------------------------------+-------------------------------------------------+----------------------------------------------------------------------------+

```

@Xenwar can you help to provide what's the ID you input? I think got 409 is correct because my devstack

**Comment by sbueringer** [comment]
@jichenjc let's wait if we get feedback from @Xenwar the next few days and otherwise close it because we cannot reproduce it.

**Comment by Xenwar** [comment]
@sbueringer Apologies for the late reply.
I have re-tested the case and can no longer reproduce it.
And, closing this issue.
